[SEDONA-411] Add RS_Rotation
apache/sedona pull request #1061
Opened 2023-10-25 22:20 UTC by furqaankhan

## Did you read the Contributor Guide?

- Yes, I have read [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-411. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?

- Add RS_Rotation
- Add GeoTransform (Java code only, didn't port to spark)

## How was this patch tested?

- Passed new tests

## Did this PR include necessary documentation updates?

- Yes, I have updated the documentation update.

2023-10-27 04:45 UTC, jiayuasu commented
@furqaankhan Is the result identical to PostGIS?

2023-10-27 12:26 UTC, furqaankhan commented
Yes it is.

2023-10-30 16:14 UTC, furqaankhan commented
@jiayuasu I want to get Kristin's opinion before merging, so don't merge yet.

2023-10-30 21:29 UTC, jiayuasu requested changes

2023-10-30 21:29 UTC, jiayuasu commented on common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
> +        thetaIJ = Math.acos((((scaleX * skewX) + (skewY * scaleY)) / (magnitudeI * magnitudeJ)));
can `magnitude` be zero or other invalid values? If so, we need to add handlers and test cases.

2023-10-31 02:12 UTC, Kontinuation requested changes

2023-10-31 02:12 UTC, Kontinuation commented on common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
> +        double offsetY = renderedImage.getTileGridYOffset();
This is not correct. `offsetX` and `offsetY` should be directly retrieved from the upperLeftX and upperLeftY components of the raster metadata.

2023-10-31 02:12 UTC, Kontinuation commented on common/src/test/java/org/apache/sedona/common/raster/RasterAccessorsTest.java
> +        double[] expected = new double[] {10.04987562112089, 10.04987562112089, -1.4711276743037347, -1.5707963267948966, 0.0, 0.0};
We are getting 0 offsets for rasters with non-zero offsets, this is caused by the problem mentioned above.

2023-10-31 19:46 UTC, jiayuasu approved these changes

2023-10-31 19:52 UTC, merged