[SEDONA-421] Add RS_Clip
apache/sedona pull request #1078
Opened 2023-11-08 17:13 UTC by furqaankhan

## Did you read the Contributor Guide?

- Yes, I have read [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-421. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?

- Add RS_Clip
- Add support to RasterUtils.getDataType to work with RS_BandPixelType

## How was this patch tested?

- Passed new test cases

## Did this PR include necessary documentation updates?

- Yes, I have updated the documentation update.

2023-11-08 20:01 UTC, jiayuasu requested changes

2023-11-08 20:01 UTC, jiayuasu commented on common/src/test/java/org/apache/sedona/common/raster/RasterBandEditorsTest.java
> +        GridCoverage2D raster = rasterFromGeoTiff(resourceFolder + "raster_geotiff_color/FAA_UTM18N_NAD83.tif");
Please add tests to try with `crop == true`. In addition, please also test if the pixels of a raster are successfully masked.

2023-11-08 20:06 UTC, furqaankhan commented on common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
> +//    public static GridCoverage2D clip(GridCoverage2D raster, int band, Geometry geometry, boolean crop) {
I thought to keep it when we can support same arity functions. We can uncomment it and use it. Do let me know if you still want them to be removed.

2023-11-08 20:07 UTC, furqaankhan commented on common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
> +        parameters.parameter("Source").setValue(singleBandRaster);
It can be either single or all bands. How do you want me to implement it?

2023-11-08 20:10 UTC, jiayuasu commented on common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
> +//    public static GridCoverage2D clip(GridCoverage2D raster, int band, Geometry geometry, boolean crop) {
OK. You can leave it there.

2023-11-08 20:22 UTC, jiayuasu commented on common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
> +        parameters.parameter("Source").setValue(singleBandRaster);
A single band is ok for now.

2023-11-09 05:19 UTC, jiayuasu approved these changes

2023-11-09 05:20 UTC, merged