[SEDONA-446] Add floating point datatype support in RS_AsBase64
apache/sedona pull request #1146
Opened 2023-12-13 23:18 UTC by furqaankhan

## Did you read the Contributor Guide?

- Yes, I have read [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-446. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?

- add support for double/floating point datatypes to RS_AsBase64

## How was this patch tested?

- passed existing tests

## Did this PR include necessary documentation updates?

- Yes, I have updated the documentation update.

2023-12-14 02:22 UTC, jiayuasu requested changes
Can you add a test case?

2023-12-14 03:54 UTC, jiayuasu commented
@furqaankhan Please fix the failed test

2023-12-15 08:18 UTC, jbampton commented on docs/api/sql/Raster-visualizer.md
> +Introduction: Returns a base64 encoded string of the given raster. If the datatype is integral then this function internally takes the first 4 bands as RGBA, and converts them to the PNG format, fina
```suggestion
Introduction: Returns a base64 encoded string of the given raster. If the datatype is integral then this function internally takes the first 4 bands as RGBA, and converts them to the PNG format, finally produces a base64 string. When the datatype is not integral, the function converts the raster to TIFF format, and then generates a base64 string. To visualize other bands, please use it together with `RS_Band`. You can take the resulting base64 string in [an online viewer](https://base64-viewer.onrender.com/) to check how the image looks like.
```

2023-12-16 03:51 UTC, jiayuasu approved these changes

2023-12-16 03:51 UTC, merged