[SEDONA-610] Add ST_IsValidTrajectory
apache/sedona pull request #1481
Opened 2024-06-19 02:32 UTC by furqaankhan

## Did you read the Contributor Guide?

- Yes, I have read the [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-610. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?

- Add ST_IsValidTrajectory

## How was this patch tested?

- add new unit tests

## Did this PR include necessary documentation updates?

- Yes, I have updated the documentation.

2024-06-19 02:43 UTC, jiayuasu requested changes
please remove `println`

2024-06-19 02:45 UTC, furqaankhan commented
It is there to provide the user with information. [Reference.](https://github.com/postgis/postgis/blob/44f71532565df5492a5c0a6e8721c097356eb627/liblwgeom/lwline.c#L454). Let me know if you still want it removed.

2024-06-19 02:47 UTC, jiayuasu commented
This is not the correct way to provide info. We should use log4j for this purpose. @Kontinuation maybe it is time to add log4j dependencies to the `sedona-common` module?

2024-06-19 02:49 UTC, furqaankhan commented
I used print statements just because the logger wasn't available to me.

2024-06-19 18:33 UTC, jiayuasu requested changes

2024-06-19 18:33 UTC, jiayuasu commented on docs/api/sql/Function.md
> +
Please add an example that returns false

2024-06-19 18:33 UTC, jiayuasu commented
@furqaankhan please still remove the println command.

2024-06-20 22:43 UTC, jiayuasu approved these changes

2024-06-20 22:44 UTC, jiayuasu approved these changes

2024-06-20 22:45 UTC, merged