[SEDONA-635] Allow ST_AsGeoJSON to return feature and featureCollection format GeoJSON
apache/sedona pull request #1530
Opened 2024-07-29 20:41 UTC by prantogg

## Did you read the Contributor Guide?

- Yes, I have read the [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-635. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?

- Adds `type` parameter to specify format of GeoJSON output.

## How was this patch tested?

- Passes new and existing tests

## Did this PR include necessary documentation updates?

- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/apache/sedona/blob/99239524f17389fc4ae9548ea88756f8ea538bb9/pom.xml#L29) in `vX.Y.Z` format.

2024-07-29 21:00 UTC, furqaankhan commented
@prantogg please open a PR on https://github.com/wherobots/sedona-snowflake-tester to test snowflake implementation.

2024-07-29 21:35 UTC, jiayuasu requested changes

2024-07-29 21:35 UTC, jiayuasu commented on common/src/main/java/org/apache/sedona/common/Functions.java
> +                + ". Valid types are: 'geometry', 'feature', 'featurecollection'.");
Shouldn't this be `simple` instead of `geometry`?

2024-07-29 21:35 UTC, jiayuasu commented on common/src/main/java/org/apache/sedona/common/Functions.java
> +        throw new IllegalArgumentException(
Please add tests for this function

2024-07-29 21:35 UTC, jiayuasu commented on docs/api/sql/Function.md
> +- "Simple" (default): Returns a simple GeoJSON geometry.
Can you add an example below for the Feature and FeatureCollection

2024-07-30 23:50 UTC, jiayuasu commented
@prantogg please fix failed Python tests

2024-07-31 04:07 UTC, jiayuasu approved these changes

2024-07-31 04:07 UTC, merged